feat: add content promotion
posit-dev/connect-cookbook pull request #101
Opened 2024-06-27 18:15 UTC by tdstein

2024-06-28 02:27 UTC, annikakrilov commented on 13-mlops/03-promoting-content/index.qmd
> +You want to promote content from one Posit Connect location to another. The location may be a different Posit Connect server or on the same server.
```suggestion
You want to promote content from one Posit Connect location to another. The location may be a different Connect server or on the same server.
```

2024-06-28 02:27 UTC, annikakrilov commented on 13-mlops/03-promoting-content/index.qmd
> +Finally, deploy the bundle on the target server. This starts a new deployment task  on the target server to render the bundle.
```suggestion
Finally, deploy the bundle on the target server. This starts a new deployment task on the target server to render the bundle.
```

2024-06-28 02:27 UTC, annikakrilov commented on 13-mlops/03-promoting-content/index.qmd
> +### Full Example
```suggestion
### Full example
```

2024-06-28 14:41 UTC, tdstein commented on 13-mlops/03-promoting-content/index.qmd
> +### Full Example
🤦🏻

2024-06-28 14:41 UTC, tdstein commented on 13-mlops/03-promoting-content/index.qmd
> +### Full Example
I don't know if I'll ever break this habit

2024-06-28 15:19 UTC, toph-allen requested changes

2024-06-28 15:19 UTC, toph-allen commented on 13-mlops/03-promoting-content/index.qmd
> +You want to promote content from one Posit Connect location to another. The location may be a different Posit Connect server or on the same server.
In addition, since the Solution here is specifically the two-server version, I think the problem here should be specific. I think even just this suffices:

> You want to deploy content from one Connect server to another Connect server.

2024-06-28 15:19 UTC, toph-allen commented on 13-mlops/03-promoting-content/index.qmd
> +Unlike other examples, this recipe creates two `Client` objects. One for the source location and one for the target location. Here we define the API keys and URL information inline. In your environme
I think "source location" and "target location" should be described in more detail — it's kind of implicit that they are two Connect servers. If describe this Problem as "deploy from one server to another" then you can just say "source and target Connect servers".

I don't think that saying "Here we define information inline" is a good replacement for having a block of user-input variables (see below). I think that having a "shopping list" of input data at the front is better for the recipes in our cookbook, because we are specifically presenting them as code you can copy or run. (In the R and Python cookbooks, they're generally implied to be excerpts from someone's interactive session, not something to be used wholesale, and I think people read those kinds of examples differently.

I don't know how I feel about the sentence about best practices, I think you can drop it. Like, either they know the practices around API keys or we need to fully explain or link to those practices.

2024-06-28 15:19 UTC, toph-allen commented on 13-mlops/03-promoting-content/index.qmd
> +target_bundle = target_content.bundles.create('bundle.tar.gz')
What's this line doing? Perhaps it should go in the "deploy the bundle" section below.

2024-06-28 15:19 UTC, toph-allen commented on 13-mlops/03-promoting-content/index.qmd
> +Optionally, wait for the deployment task to complete.
What does waiting for the deployment task do? As the person reading this to learn about the SDKs, I… personally don't know what this function would do.

Maybe this function literally just blocks until the deployment is done in case you want to use code that calls the deployed bundle, and returns an error if the deployment fails so you can see its status. In that case, I'd say that explicitly. Soft suggestion: if this is the only way they'll see an error message on failure, we shouldn't call this optional.

Something like:

```suggestion
Wait for the deployment task to complete. The `wait_for()` function will watch the deployment process, only returning successfully once it completes, and returning an error if it fails. This allows you to call the deployed content via Connect's API later in the same script.
```

2024-06-28 15:19 UTC, toph-allen commented on 13-mlops/03-promoting-content/index.qmd
> +source_bundle = source_content.bundles.get('your-bundle-id')
If you just get the default bundle (which is the most common case) how do you do that? We should do that here, and save the specific bundle case for the latest. Otherwise, I don't know how to use this script to do the default thing.

2024-06-28 15:19 UTC, toph-allen commented on 13-mlops/03-promoting-content/index.qmd
> +deployment_task.wait_for()
🚨 I don't actually know how to get the latest bundle, so that line is incorrect — don't use this verbatim. 🚨

```suggestion
from posit import connect

SOURCE_API_KEY = "0d23c00de05a787ec2079ef75a881cdb"
SOURCE_URL = "https://connect1.company.co/"
SOURCE_GUID = "154bd2af-e8fa-4aa4-aab8-dcef701f4af9"
TARGET_API_KEY = "f19eb24c1fde2370e621ccdaf347f15e"
TARGET_URL = "https://connect1.company.co/"
TARGET_GUID = "2d178c46-4dca-40b0-bf22-a21e1cfb5b46"

source_client = connect.Client(api_key=SOURCE_API_KEY, url=SOURCE_URL)
target_client = connect.Client(api_key=TARGET_API_KEY, url=TARGET_URL)

source_content = source_client.content.get(SOURCE_GUID)
target_content = target_client.content.get(TARGET_GUID)

source_bundle = source_content.bundles.get('your-bundle-id')

source_bundle.download('bundle.tar.gz')
target_bundle = target_content.bundles.create('bundle.tar.gz')

deployment_task = target_bundle.deploy()
deployment_task.wait_for()
```

2024-06-28 16:00 UTC, tdstein commented on 13-mlops/03-promoting-content/index.qmd
> +You want to promote content from one Posit Connect location to another. The location may be a different Posit Connect server or on the same server.
That's a good point. We could make a separate recipe for that example, although a savvy user will probably be able to connect the dots.

2024-06-28 16:03 UTC, tdstein commented on 13-mlops/03-promoting-content/index.qmd
> +target_client = connect.Client(api_key='your-target-api-key', url='your-target-url')
Thanks! After our discussion yesterday, I meant to do this but forgot to circle back.

I would like to link to the document on viewing content information and finding content once that is ready.

2024-07-01 21:29 UTC, toph-allen approved these changes
The promoting content Python code looks great! Keeping the R on my to do list.

2024-07-01 21:29 UTC, toph-allen commented on 14-mlops/03-promoting-content-from-staging-to-production/index.qmd
> +Unlike other examples, this recipe creates two client objects. One for the statging server and one for the production location. In this example, the *source* server is the staging server and *target*
```suggestion
Unlike other examples, this recipe creates two client objects: one for the staging server and one for the production server. In this example, the *source* server is the staging server and *target* server is the production server. These concepts can be adjusted to fit your organizational needs.
```

2024-07-02 14:58 UTC, tdstein commented on 14-mlops/03-promoting-content-from-staging-to-production/index.qmd
> +Finally, wait for the deployment task to complete. The `wait_for()` method will watch the deployment process and return once it completes. Check the status and returning an error if it fails. See ["V
Thanks. I applied your feedback and added some more information to that sentence.

2024-07-02 14:58 UTC, merged